/**
 * What a couple enters on the guest invites step, and the address they are
 * given.
 *
 * The address is not one of the things they enter. The backend generates the
 * Invitation Slug when an invitation is created without one, and there is no
 * endpoint to ask whether a name is taken - so a couple who picked their own
 * could only be told it was gone after failing. The field shows the slug and
 * takes no typing, and this module has no rules to hold it to: they would be
 * rules for something nobody types, checking a value nobody here produced.
 *
 * Nothing here reaches a network. Everything is composed from what the flow
 * already holds.
 */

import type { GuestList } from './guest-list';

/** What a couple enters on the guest invites step. */
export interface GuestInvitesValues {
  /**
   * The Invitation Slug the invitation is published under. Generated by the
   * backend rather than chosen, so nothing on the step writes to it.
   */
  slug: string;
  /** The message a guest receives, with placeholders still in it. */
  greetingMessage: string;
  /**
   * The Guest List, as read from the CSV they uploaded and then corrected, or
   * null until they have uploaded one.
   *
   * Which of those it is decides which of the two states the design draws for
   * this step is showing.
   */
  guestList: GuestList | null;
}

/**
 * The fixed part of the address, printed ahead of the slug.
 *
 * The design draws the chosen name as a subdomain, and the shareable link is a
 * path instead: see `docs/adr/0001-path-urls-not-subdomains.md`. The path
 * carries the template as well as the slug, because more wedding templates are
 * expected and an address that named only the slug could not tell them apart.
 */
export const SLUG_PREFIX = 'memoify.live/wedding-1/';

/**
 * The query parameter an invitation's slug can be supplied by, while the flow
 * has no way to learn one.
 *
 * The slug is the backend's to generate. The flow now creates the invitation it
 * generates the slug for, and still cannot read it: the create call answers with
 * the identifier and nothing else, so learning the address means reading the
 * invitation back. Until that happens a flow has no address at all - which is
 * the truth, and which leaves the published step with nothing to show on a
 * screen whose whole point is the address.
 *
 * This is how it is told one: the same scaffolding shape the Showcase uses for
 * its Example Content and its addressee, opt-in, and drawn from nowhere by
 * default so that no couple is ever shown somebody else's name as their own. It
 * comes out in `hbd-ox7.9`, when a published invitation has an address to show.
 */
export const SLUG_PARAM = 'slug';

/** The slug a query gave, or none, in which case there is no address yet. */
export function slugFrom(value: string | string[] | undefined): string {
  const slug = Array.isArray(value) ? value[0] : value;
  return slug?.trim() ?? '';
}

/** The placeholders the greeting message is written in terms of. */
export const GUEST_MESSAGE_PLACEHOLDERS = {
  brideNickname: '[Bride Nickname]',
  groomNickname: '[Groom Nickname]',
  guestName: '[Guest Name]',
  guestLink: '[Generated Guest Link]',
} as const;

/** The message the design starts a couple off with, placeholders and all. */
export const DEFAULT_GUEST_MESSAGE = [
  'The Wedding of [Bride Nickname] & [Groom Nickname]',
  '',
  'Dear [Guest Name],',
  '',
  'With joyful hearts, we would like to invite you to celebrate our wedding and be part of one of the most meaningful days of our lives.',
  '',
  'Your presence and blessings would mean so much to us as we begin this beautiful new chapter together.',
  '',
  'Please find the details of our wedding celebration through the invitation link below:',
  '',
  '[Generated Guest Link]',
  '',
  'We truly hope you can join us and share this special moment with our family and loved ones.',
  '',
  'With love and gratitude,',
  '[Bride Nickname] & [Groom Nickname]',
].join('\n');

/** The guest the preview addresses, so a couple sees a name rather than a slot. */
export const SAMPLE_GUEST_NAME = 'Johnny';

/**
 * Where a published invitation lives, or null while it has no slug.
 *
 * Null rather than a link built from an empty slug: an address showing
 * `https://memoify.live/wedding-1/` would be telling the couple something
 * untrue about what they are about to send. Nothing else is checked, because
 * nothing else is ours to check - the slug comes from the backend, and a
 * malformed one is neither something a couple caused nor something they could
 * fix.
 *
 * The shape is a path carrying the template, per
 * `docs/adr/0001-path-urls-not-subdomains.md`, and the field the couple reads it
 * in shows the same path ahead of the box rather than a subdomain after it. The
 * design draws a subdomain, which the product cannot serve; showing it would
 * promise an address that does not resolve.
 */
export function invitationLinkFor(slug: string): string | null {
  const value = slug.trim();
  if (value === '') return null;
  return `https://${SLUG_PREFIX}${value}`;
}

/**
 * The link one guest would receive, or null while there is no address yet.
 *
 * The same address as the invitation itself, naming the guest it was written
 * for, so the invitation can greet them.
 */
export function guestLinkFor(slug: string, guestName: string): string | null {
  const invitation = invitationLinkFor(slug);
  if (!invitation) return null;
  return `${invitation}?name=${guestName.trim().toLowerCase()}`;
}

export interface GuestMessageSubstitutions {
  brideNickname: string;
  groomNickname: string;
  guestName: string;
  guestLink: string | null;
}

/**
 * The greeting message as one guest will actually receive it.
 *
 * A placeholder with nothing to put in its place is left standing rather than
 * blanked, so the couple can see which part of their message is still waiting
 * on them.
 */
export function renderGuestMessage(
  message: string,
  {
    brideNickname,
    groomNickname,
    guestName,
    guestLink,
  }: GuestMessageSubstitutions
): string {
  const replacements: [string, string | null][] = [
    [GUEST_MESSAGE_PLACEHOLDERS.brideNickname, brideNickname],
    [GUEST_MESSAGE_PLACEHOLDERS.groomNickname, groomNickname],
    [GUEST_MESSAGE_PLACEHOLDERS.guestName, guestName],
    [GUEST_MESSAGE_PLACEHOLDERS.guestLink, guestLink],
  ];

  return replacements.reduce(
    (text, [placeholder, value]) =>
      value ? text.split(placeholder).join(value) : text,
    message
  );
}
